version: "3"
services:
  angular-app:
    build: ./restaurant_angular
    container_name: client_container
    ports:
      - "3000:3000"
    networks:
      - spring-network
    volumes:
      - ./restaurant_angular:/app
      - /app/node_modules
  springboot-app:
    container_name: jjjjjj
    restart: always
    build: ./restaurant_spring
    ports:
      - 5050:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    networks:
      - spring-network

  mysqldb:
    container_name: hhhhhhh
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3070:3306
    environment:
      MYSQL_DATABASE: restaurant_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - spring-network

volumes:
  mysql-data:
networks:
  spring-network:
